doc/builders/mages: improve shadowSetup reference
The snippet will fail with this error as it is not self contained and assumes `shadowSetup` was given:

    $ nix-build docker-image.nix 
    error: undefined variable 'shadowSetup' at docker-image.nix:20:7

Instead use the full reference to `shadowSetup` in the example snippet so it will always work.